# Generated by Django 3.2.13 on 2023-07-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230704_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_prise_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
